### ISSUE TITLE
Rapid Re-rendering 

### ISSUE THREAD

**Issue by sethiroth66** [Idlepunk/Idlepunk.github.io#5] opened 2016-10-05 20:42 UTC
Once reaching the upgrade for auto-generating the entity prior. 
The "Doubles the income of each .." text gets rapidly re-drawn to the screen.

**Comment by Idlepunk** [comment] 2016-10-05 22:21
I couldn't reproduce this, but it should be fixed now anyway. If it's still happening could you please send me the exported save?

**Closed as completed** 2016-10-05 22:21 UTC

**Comment by sethiroth66** [comment] 2016-10-05 22:43
Just checked, looks like its still being re-drawn in element inspector.
Seems to only be happening to the descriptions with the appended "For every $X you will generate 0.1 $Y."

Chrome Version 53.0.2785.143 m
Save: eyJkYXRhSGFja2VkIjoxMjA5NTMxNC43LCJ0b3RhbERhdGFIYWNrZWQiOjE5MjI5ODMxLjcsImN1cnJlbnRUaGVtZSI6MCwibGV0IjpbeyJuZXh0VXBncmFkZUNvc3QiOjEzMzEsIml0ZW1Db3VudCI6OCwidXBncmFkZUNvdW50IjowLCJhdXRvQnV5Q291bnQiOjB9LHsibmV4dFVwZ3JhZGVDb3N0IjoxNDY0MTAwMCwiaXRlbUNvdW50Ijo1LCJ1cGdyYWRlQ291bnQiOjMsImF1dG9CdXlDb3VudCI6MH0seyJuZXh0VXBncmFkZUNvc3QiOjE2MTA1MSwiaXRlbUNvdW50Ijo4LCJ1cGdyYWRlQ291bnQiOjAsImF1dG9CdXlDb3VudCI6MH0seyJuZXh0VXBncmFkZUNvc3QiOjE3NzE1NjEsIml0ZW1Db3VudCI6NSwidXBncmFkZUNvdW50IjowLCJhdXRvQnV5Q291bnQiOjB9LHsibmV4dFVwZ3JhZGVDb3N0IjoxOTQ4NzE3MSwiaXRlbUNvdW50Ijo1LCJ1cGdyYWRlQ291bnQiOjAsImF1dG9CdXlDb3VudCI6MH0seyJuZXh0VXBncmFkZUNvc3QiOjIxNDM1ODg4MSwiaXRlbUNvdW50IjowLCJ1cGdyYWRlQ291bnQiOjAsImF1dG9CdXlDb3VudCI6MH0seyJuZXh0VXBncmFkZUNvc3QiOjIzNTc5NDc2OTEsIml0ZW1Db3VudCI6MCwidXBncmFkZUNvdW50IjowLCJhdXRvQnV5Q291bnQiOjB9LHsibmV4dFVwZ3JhZGVDb3N0IjoyNTkzNzQyNDYwMSwiaXRlbUNvdW50IjowLCJ1cGdyYWRlQ291bnQiOjAsImF1dG9CdXlDb3VudCI6MH0seyJuZXh0VXBncmFkZUNvc3QiOjI4NTMxMTY3MDYxMSwiaXRlbUNvdW50IjowLCJ1cGdyYWRlQ291bnQiOjAsImF1dG9CdXlDb3VudCI6MH0seyJuZXh0VXBncmFkZUNvc3QiOjMxMzg0MjgzNzY3MjEsIml0ZW1Db3VudCI6MCwidXBncmFkZUNvdW50IjowLCJhdXRvQnV5Q291bnQiOjB9LHsibmV4dFVwZ3JhZGVDb3N0IjozNDUyMjcxMjE0MzkzMSwiaXRlbUNvdW50IjowLCJ1cGdyYWRlQ291bnQiOjAsImF1dG9CdXlDb3VudCI6MH0seyJuZXh0VXBncmFkZUNvc3QiOjM3OTc0OTgzMzU4MzI0MSwiaXRlbUNvdW50IjowLCJ1cGdyYWRlQ291bnQiOjAsImF1dG9CdXlDb3VudCI6MH0seyJuZXh0VXBncmFkZUNvc3QiOjQxNzcyNDgxNjk0MTU2NTEsIml0ZW1Db3VudCI6MCwidXBncmFkZUNvdW50IjowLCJhdXRvQnV5Q291bnQiOjB9XX0=
